name: Eastleigh Osteopathic Clinic
favicon: null
layout_spectrum: 0.30253106681630015
typography_spectrum: 0.7218676707707345
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2693835732061416
  lightness: 0.09588298737071455
  saturation: 0.627743566641584
  rhythmicContrast: 0.02213679440319538
purpose: []
